name = "planner-ai"
main = "worker.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "planner-db"
database_id = "796e078d-7095-4add-a7c7-4e9749df1e48"

[triggers]
crons = ["* * * * *"]
